name: CI2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@a01907d086f900f2a8d89f5a4a2ec2d5ae8c3d2e9d1
        with:
          php-version: '8.1'
          extensions: mbstring, pdo_mysql, exif
          tools: composer:v2

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Install dependencies via Composer
        working-directory: apiato-app
        run: |
          composer install --no-progress --prefer-dist --no-scripts
